### ISSUE TITLE
/etc/grub.d/09_optimus: line 211: version_find_latest: command not found

### ISSUE THREAD

**Issue by 0x241F31** [hakasapl/optimus-manager-grub#2]
I'm getting this error when trying to install this script to grub
After --uninstall it works again without errors.
I'm using grub 2:2.06.r297.g0c6c1aff2-1

**Comment by ItsLiyua** [comment]
Same for me.
Any ideas why this is happening?
I don't know bash well enough to debug scripts.

**Comment by hakasapl** [comment]
Is this on Arch? Looks like this command was removed in recent versions of GRUB, so I may have to edit my script. But that doesn't explain why it would work after the uninstall

**Comment by milos7250** [comment]
I'm having the same problem and I'm on Arch. The grub version I have installed shows up as 2:2.06.r322.gd9b4638c5-4.

**Comment by ItsLiyua** [comment]
> Is this on Arch? Looks like this command was removed in recent versions of GRUB, so I may have to edit my script. But that doesn't explain why it would work after the uninstall

The script doesn't work after uninstalling but the `grub-mkconfig`-command can be used again. While the script is installed you cannot use `grub-mkconfig`.

**Comment by hakasapl** [comment]
Okay, I was able to reproduce and (hopefully) push a fix with 8654e72039c4037d958f9e44f5545ba10c2d0add.

Please pull the repo again and run `./install.sh` again and let me know if things are working now.

**Comment by milos7250** [comment]
I can confirm that the fix worked, I could run grub-mkconfig and the boot menu entries generated correctly
